### ISSUE TITLE
std::cout fails after one write

### ISSUE THREAD

**Issue by Cryptogenic** [OpenOrbis/OpenOrbis-PS4-Toolchain#53] opened 2020-06-24 01:23 UTC
When writing to the `std::cout` output stream, after one operand passes through the `<<` operator, the badbit and failbit is set on the stream and no further operands are processed. For example, if you compile:

```cpp
#include <iostream>

int main()
{
    std::cout << "Test 1 " << "Test 2" << std::endl;
    return 0;
}
```

Your output would look like this:

```
Test 1 
```

"Test 2" doesn't make it to stdout. I discovered ultimately the failbit gets set by the ostream's `__put_character_sequence` template when calling `__pad_and_output()`.

[src](https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain/blob/master/include/c%2B%2B/v1/ostream#L778)
```cpp
template<class _CharT, class _Traits>
basic_ostream<_CharT, _Traits>&
__put_character_sequence(basic_ostream<_CharT, _Traits>& __os,
                          const _CharT* __str, size_t __len)
{
#ifndef _LIBCPP_NO_EXCEPTIONS
    try
    {
#endif  // _LIBCPP_NO_EXCEPTIONS
        typename basic_ostream<_CharT, _Traits>::sentry __s(__os);
        if (__s)
        {
            typedef ostreambuf_iterator<_CharT, _Traits> _Ip;
            if (__pad_and_output(_Ip(__os),
                                 __str,
                                 (__os.flags() & ios_base::adjustfield) == ios_base::left ?
                                     __str + __len :
                                     __str,
                                 __str + __len,
                                 __os,
                                 __os.fill()).failed())
                __os.setstate(ios_base::badbit | ios_base::failbit); // <---- Specter: badbit and failbit are set here
        }
#ifndef _LIBCPP_NO_EXCEPTIONS
    }
    catch (...)
    {
        __os.__set_badbit_and_consider_rethrow();
    }
#endif  // _LIBCPP_NO_EXCEPTIONS
    return __os;
}
```

What's odd is `ostream` is used by a lot of other streams, `std::stringstream` and `std::ofstream` for instance, however these two work fine, it's only `std::cout` specifically that has an issue.

Currently samples use a [logging class](https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain/blob/master/samples/_common/log.h) which functions similar to `std::cout`, but this is hacky, and fixing `cout` directly would be ideal if possible. Help would be greatly appreciated here as the libcxx codebase is complex and my previous attempts at root causing this have been unsuccessful.

**Comment by sleirsgoevy** [comment] 2020-08-06 13:21
**Note: I am on FW 6.72**

Possibly I've found the cause of the error:

```
(gdb) x/1i $pc
=> 0x644508d4 <__stdio_write+69>:	syscall 
(gdb) p $rax
$1 = 121
(gdb) p $rdi
$2 = 1
(gdb) p {char*[4]}$rsi
$3 = {0x6450e008 "", 0x0, 0x644c6503 "Hello world! Waiting ", 0x15 <error: Cannot access memory at address 0x15>}
(gdb) p $rdx
$4 = 2
(gdb) stepi
0x00000000644508d6 in __stdio_write ()
(gdb) p $rax
$5 = 0
(gdb) 
```

Here we can see that for some reason writev() only uses the first iovec (of length 0), and thus reports that it has written 0 bytes. After that __stdio_write gets stuck in a retry loop, writing 0 of 21 bytes on each iteration.

**Comment by nkrapivin** [comment] 2021-12-03 16:04
This is fixed in https://github.com/OpenOrbis/musl/commit/644df6a7b591f7aca258c4702c7f271dd18a65d8

**Closed** 2021-12-03 16:08 UTC
Labels: bug, help wanted
